base_path: /

routes:
  PromPacificCatalogueUa:   [/catalogue/pacifictea/export/prom/view/xml, Application\Modules\Prom\PacificTea\Controllers\CatalogueController.exportAction, GET]
  PromLecabaretCatalogueUa: [/catalogue/nothingshop/export/prom/view/xml, Application\Modules\Prom\Nothingshop\Controllers\CatalogueController.exportAction, GET]