base_path: /

routes:
  GoogleMerchantCatalogue:  [/catalogue/pacifictea/export/googlemerchant/view/xml, Application\Modules\GoogleMerchant\Controllers\CatalogueController.exportAction, GET]
  GoogleMerchantOrder:      [/order/pacifictea/export/googlemerchant/view/xml, Application\Modules\GoogleMerchant\Controllers\OrderController.exportAction, GET]
  AmazonPredadCatalogue:    [/catalogue/pacifictea/export/amazon/view/xml, Application\Modules\Amazon\Controllers\CatalogueController.exportAction, GET]
  AmazonOrder:              [/order/pacifictea/export/amazon/view/xml, Application\Modules\Amazon\Controllers\OrderController.exportAction, GET]
  PromCatalogueUa:          [/catalogue/pacifictea/export/prom/view/xml, Application\Modules\Prom\Controllers\CatalogueController.exportAction, GET]